services:
  app:
    image: ghcr.io/breezybuddy69/halo4-website:main
    container_name: halovision-website
    restart: unless-stopped
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.halovision.rule=Host(`halovisionai.cloud`)"
      - "traefik.http.routers.halovision.entrypoints=websecure"
      - "traefik.http.routers.halovision.tls=true"
      - "traefik.http.routers.halovision.tls.certresolver=letsencrypt"
      - "traefik.http.services.halovision.loadbalancer.server.port=8081"

networks:
  traefik-proxy:
    external: true
